base: &base
  adapter: sqlite3
  timeout: 5000

development:
  database: db/development.sqlite3
  <<: *base

test:
  database: db/test.sqlite3
  <<: *base

private:
  database: db/private.sqlite3
  <<: *base

production:
  database: production_pw_pusher
  host: 127.0.0.1
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: barebones_pw
  password: B@rebones_1
