base: &base
  host: 127.0.0.1
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: testpushpw
  password: testpushpw

development:
  database: dev_testpushpw
  <<: *base

test:
  database: test_testpushpw
  <<: *base

production:
  database: heroku_testpushpw
  <<: *base
